"""Add sugar and calcium columns to Food table

Revision ID: 1d2663c6a5c6
Revises: 
Create Date: 2025-04-29 20:25:00.027546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2663c6a5c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sugar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcium', sa.Float(), nullable=True))

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sugar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcium', sa.Float(), nullable=True))

    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculated_sugar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculated_calcium', sa.Float(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sugar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_calcium', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('total_calcium')
        batch_op.drop_column('total_sugar')

    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_column('calculated_calcium')
        batch_op.drop_column('calculated_sugar')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('calcium')
        batch_op.drop_column('sugar')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('calcium')
        batch_op.drop_column('sugar')

    # ### end Alembic commands ###
