"""Initial schema with recipes and ingredients

Revision ID: 3b60683b3fd2
Revises: 
Create Date: 2025-04-29 23:17:01.767559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b60683b3fd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_unit', sa.String(length=50), nullable=False),
    sa.Column('base_quantity', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods')),
    sa.UniqueConstraint('name', name=op.f('uq_foods_name'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('typical_unit', sa.String(length=50), nullable=False),
    sa.Column('unit_quantity', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_name'), ['name'], unique=True)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('meal_type_suitability', sa.String(length=100), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.Column('total_fiber', sa.Float(), nullable=True),
    sa.Column('total_sugar', sa.Float(), nullable=True),
    sa.Column('total_calcium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_name'), ['name'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity_consumed', sa.Float(), nullable=False),
    sa.Column('calculated_calories', sa.Float(), nullable=False),
    sa.Column('calculated_protein', sa.Float(), nullable=False),
    sa.Column('calculated_carbs', sa.Float(), nullable=False),
    sa.Column('calculated_fat', sa.Float(), nullable=False),
    sa.Column('calculated_fiber', sa.Float(), nullable=True),
    sa.Column('calculated_sugar', sa.Float(), nullable=True),
    sa.Column('calculated_calcium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(food_id IS NOT NULL AND recipe_id IS NULL) OR (food_id IS NULL AND recipe_id IS NOT NULL)', name=op.f('ck_meal_logs_meal_log_source_check')),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_meal_logs_food_id_foods')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_meal_logs_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_logs'))
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_logs_log_date'), ['log_date'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_ingredients_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients'))
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_ingredient_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_log_date'))

    op.drop_table('meal_logs')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_name'))

    op.drop_table('recipes')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_name'))

    op.drop_table('ingredients')
    op.drop_table('foods')
    # ### end Alembic commands ###
