"""Add Nutrionix lookup fields to Ingredient

Revision ID: 89c818a59c0b
Revises: 3b60683b3fd2
Create Date: 2025-04-30 21:12:26.711473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c818a59c0b'
down_revision = '3b60683b3fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('api_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('api_info', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('api_info')
        batch_op.drop_column('api_name')
        batch_op.drop_column('data_source')

    # ### end Alembic commands ###
