"""Added micro columns (Fe, K, Na, VitD) and API fields

Revision ID: b3552809adf7
Revises: 89c818a59c0b
Create Date: 2025-05-01 07:37:01.837297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3552809adf7'
down_revision = '89c818a59c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iron', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('potassium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vit_d', sa.Float(), nullable=True))

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iron', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('potassium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vit_d', sa.Float(), nullable=True))

    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculated_iron', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculated_potassium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculated_sodium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calculated_vit_d', sa.Float(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_iron', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_potassium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sodium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_vit_d', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('total_vit_d')
        batch_op.drop_column('total_sodium')
        batch_op.drop_column('total_potassium')
        batch_op.drop_column('total_iron')

    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_column('calculated_vit_d')
        batch_op.drop_column('calculated_sodium')
        batch_op.drop_column('calculated_potassium')
        batch_op.drop_column('calculated_iron')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('vit_d')
        batch_op.drop_column('sodium')
        batch_op.drop_column('potassium')
        batch_op.drop_column('iron')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('vit_d')
        batch_op.drop_column('sodium')
        batch_op.drop_column('potassium')
        batch_op.drop_column('iron')

    # ### end Alembic commands ###
