"""Added micronutrients from Nutritionix and JSON fields to models

Revision ID: ed54dfbe9a13
Revises: b3552809adf7
Create Date: 2025-05-01 13:39:38.294230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed54dfbe9a13'
down_revision = 'b3552809adf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_details', sa.JSON(), nullable=True))

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('other_details')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('other_details')

    # ### end Alembic commands ###
